[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"
  environment = { NODE_ENV = "development", NODE_VERSION = "16.16.0" }

[context.production.environment]
  NODE_ENV = "production"
  NODE_VERSION = "16.16.0"